before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
addons:
  apt:
    packages:
    - libgtk-3-common
    - libgtk-3-dev
    - python3-gi
    - python-gi
sudo: false
language: python
python:
  - "3.3" #Ezhil boots on Python 3
  - "2.7"
  - "2.6"
#  - "pypy" #unittests are broke in PyPy
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors ordereddict; fi
  - python setup.py install && pip install argparse
  - pip install .
  - pip install nose-cov
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]];  then ./test3; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];  then ./unittest && ./test;  fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];  then ./unittest && ./test;  fi
# TBD: based on Travis' support; until them summa keda
#  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]];  then cd editor && python testdriver.py; fi
#  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];  then cd editor && python testdriver.py; fi
